#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# If no service name was specified
if [[ -z "$2" ]]; then
  echo "Missing name of service to uninstall" >&2
  exit 1
fi

# For each service specified
while [[ -n "$2" ]]; do

  # If that service exists, uninstall it
  if [[ -d "$PLUSHU_SERVICES_DIR/$2" ]]; then
    "$PLUSHU_ROOT/lib/plushook" uninstall-service "$2"

  # If that service does not exist
  else
    echo "Service not found: $2" >&2
    exit 1
  fi
  shift
done
